name: Run tests

on: [ push, pull_request ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        python-version: [ "3.10" ]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      # Java 8 is the default on Mac and Windows runners, but 11 is required
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install antlr4-tools
          pip list

      - name: Generate parser
        working-directory: project/litegql/grammar
        run: antlr4 LiteGQL.g4 -visitor -Dlanguage=Python3

      - name: Test with pytest
        run: python ./scripts/run_tests.py
